### PR TITLE
Android support and Password field type

### PR DESCRIPTION
**Pull request by soulglo**
Separated these out.. apologies for the mess of reverts and commits!

### CODE REVIEW

**Comment by adamkearsley** [comment]
This PR fixes a number of Android issues, but also breaks the event listeners.

**Comment by FokkeZB** [comment]
@soulglo are you still working on this PR?

@adamkearsley if he's not, can you fork his PR and improve on it?

**Comment by adamkearsley** [comment]
@FokkeZB This must be forked from an early release as it seems to break lots of things.
I now have your Master branch working with a few tweaks.
Android is my next target... ill reference soulglo's fixes and update when i have it working.

**Comment by soulglo** [comment]
@FokkeZB @adamkearsley Sorry guys for leaving this hanging - haven't been able to spend any more time on this.

**Comment by FokkeZB** [comment]
Closing for lack of activity

**Pull request closed without merging**
